name: Check

on:
  pull_request:

  push:
    branches:
      - main # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      cmd: |
        sbt validateCode

  tests:
    name: Tests
    needs:
      - "check-code-style"
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      java: 21, 17
      scala: 2.12.x, 2.13.x, 3.x
      cmd: scripts/test-code.sh
